name: Build and Push Locust Kazoo Image

on:
  push:
    paths:
      - 'Dockerfile'
      - 'locustfile.py'
      - 'requirements.txt'
      - '.github/workflows/docker-build.yml'
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: athul07/locust-kazoo:latest
